'use client'
require('dotenv').config()
import './globals.css'

import Navbar from '@/components/Navbar'
import WorkoutStore from "@/stores/workoutStore"
import CounterStore from '@/stores/counterStore'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0" />
      </head>
      <body>
        <WorkoutStore.Provider>
          <Navbar/>
          <div className="pages">
            {children}
          </div>
        </WorkoutStore.Provider>
      </body>
    </html>
  )
}
