require('dotenv').config()
import './globals.css'
import { Suspense } from 'react'
import ClientOnly from '@/_components/ClientOnly'
import Store from '@/_stores/Store'
import Navbar from '@/_components/Navbar'
import NavigationEvents from '@/_components/NavigationEvents'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0" />
      </head>
      <body>
        {/* <ClientOnly> */}
          <Store>
            {/* <Suspense fallback={null}>
              <NavigationEvents />
            </Suspense> */}
            <Navbar/>
            <div className="pages">
              {children}
            </div>
          </Store>
        {/* </ClientOnly> */}
      </body>
    </html>
  )
}
