import Head from 'next/head'
import InitStyle from './InitStyle'
import RehydratedStores from './_stateManagement/RehydratedStores'
import Navbar from './_components/Navbar'
import PageAuth from './_components/PageAuth'


export const metadata = {
  title: 'Event Tracker',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {
  return (
    <>
      <Head>
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;700&display=swap" rel="stylesheet"/>
      </Head>
      <RehydratedStores>
        <PageAuth/>
        <InitStyle/>
        <Navbar/>
        {children}
      </RehydratedStores>
    </>
  )
}
