import './globals.css'
import Navbar from '@/_components/Navbar'
import NavigationEvents from '../admin/_components/NavigationEvents'
import RehydratedStores from '@/_stateManagement/RehydratedStores'
import PageAuth from '@/_components/PageAuth'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {
  return (
    <RehydratedStores>
      <PageAuth/>
      <NavigationEvents/>
      <Navbar/>
      <div className="pages">
        {children}
      </div>
    </RehydratedStores>
  )
}
