import Head from 'next/head'
import InitStyle from './InitStyle'
import Store from './_store/Store'
import Navbar from './_components/Navbar'


export const metadata = {
  title: 'Event Tracker',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {
  return (
    <>
      <Head>
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;700&display=swap" rel="stylesheet"/>
      </Head>
      <Store>
        <InitStyle/>
        <Navbar/>
        {children}
      </Store>
    </>
  )
}
